# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_liveness_probe_tcp_socket import IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket

class TestIoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket:
        """Test IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket(
                host = '',
                port = None
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket(
                port = None,
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerLivenessProbeTcpSocket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
