# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_dns_config_options_inner import IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner

class TestIoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner(
                name = '',
                value = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecDnsConfigOptionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
