# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_http_trigger_spec_ingressconfig import IoFissionV1HTTPTriggerSpecIngressconfig

class TestIoFissionV1HTTPTriggerSpecIngressconfig(unittest.TestCase):
    """IoFissionV1HTTPTriggerSpecIngressconfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1HTTPTriggerSpecIngressconfig:
        """Test IoFissionV1HTTPTriggerSpecIngressconfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1HTTPTriggerSpecIngressconfig`
        """
        model = IoFissionV1HTTPTriggerSpecIngressconfig()
        if include_optional:
            return IoFissionV1HTTPTriggerSpecIngressconfig(
                annotations = fission_client.models.annotations.annotations(),
                host = '',
                path = '',
                tls = ''
            )
        else:
            return IoFissionV1HTTPTriggerSpecIngressconfig(
        )
        """

    def testIoFissionV1HTTPTriggerSpecIngressconfig(self):
        """Test IoFissionV1HTTPTriggerSpecIngressconfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
