# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_package_status import IoFissionV1PackageStatus

class TestIoFissionV1PackageStatus(unittest.TestCase):
    """IoFissionV1PackageStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1PackageStatus:
        """Test IoFissionV1PackageStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1PackageStatus`
        """
        model = IoFissionV1PackageStatus()
        if include_optional:
            return IoFissionV1PackageStatus(
                buildlog = '',
                buildstatus = '',
                last_update_timestamp = fission_client.models.last_update_timestamp.lastUpdateTimestamp()
            )
        else:
            return IoFissionV1PackageStatus(
        )
        """

    def testIoFissionV1PackageStatus(self):
        """Test IoFissionV1PackageStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
