# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_cinder import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder(
                fs_type = '',
                read_only = True,
                secret_ref = fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_cinder_secret_ref.io_fission_v1_Environment_spec_builder_podspec_volumes_inner_cinder_secretRef(
                    name = '', ),
                volume_id = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder(
                volume_id = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
