# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_message_queue_trigger_spec_functionref import IoFissionV1MessageQueueTriggerSpecFunctionref

class TestIoFissionV1MessageQueueTriggerSpecFunctionref(unittest.TestCase):
    """IoFissionV1MessageQueueTriggerSpecFunctionref unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1MessageQueueTriggerSpecFunctionref:
        """Test IoFissionV1MessageQueueTriggerSpecFunctionref
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1MessageQueueTriggerSpecFunctionref`
        """
        model = IoFissionV1MessageQueueTriggerSpecFunctionref()
        if include_optional:
            return IoFissionV1MessageQueueTriggerSpecFunctionref(
                functionweights = fission_client.models.functionweights.functionweights(),
                name = '',
                type = ''
            )
        else:
            return IoFissionV1MessageQueueTriggerSpecFunctionref(
                name = '',
                type = '',
        )
        """

    def testIoFissionV1MessageQueueTriggerSpecFunctionref(self):
        """Test IoFissionV1MessageQueueTriggerSpecFunctionref"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
