# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_windows_options import IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions

class TestIoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions:
        """Test IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions(
                gmsa_credential_spec = '',
                gmsa_credential_spec_name = '',
                host_process = True,
                run_as_user_name = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerSecurityContextWindowsOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
