# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_sleep import IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep

class TestIoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep:
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep(
                seconds = 56
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep(
                seconds = 56,
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartSleep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
