# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_http_trigger_spec import IoFissionV1HTTPTriggerSpec

class TestIoFissionV1HTTPTriggerSpec(unittest.TestCase):
    """IoFissionV1HTTPTriggerSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1HTTPTriggerSpec:
        """Test IoFissionV1HTTPTriggerSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1HTTPTriggerSpec`
        """
        model = IoFissionV1HTTPTriggerSpec()
        if include_optional:
            return IoFissionV1HTTPTriggerSpec(
                createingress = True,
                functionref = fission_client.models.io_fission_v1_http_trigger_spec_functionref.io_fission_v1_HTTPTrigger_spec_functionref(
                    functionweights = fission_client.models.functionweights.functionweights(), 
                    name = '', 
                    type = '', ),
                host = '',
                ingressconfig = fission_client.models.io_fission_v1_http_trigger_spec_ingressconfig.io_fission_v1_HTTPTrigger_spec_ingressconfig(
                    annotations = fission_client.models.annotations.annotations(), 
                    host = '', 
                    path = '', 
                    tls = '', ),
                keep_prefix = True,
                method = '',
                methods = [
                    ''
                    ],
                prefix = '',
                relativeurl = ''
            )
        else:
            return IoFissionV1HTTPTriggerSpec(
                functionref = fission_client.models.io_fission_v1_http_trigger_spec_functionref.io_fission_v1_HTTPTrigger_spec_functionref(
                    functionweights = fission_client.models.functionweights.functionweights(), 
                    name = '', 
                    type = '', ),
        )
        """

    def testIoFissionV1HTTPTriggerSpec(self):
        """Test IoFissionV1HTTPTriggerSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
