# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_security_context import IoFissionV1EnvironmentSpecBuilderContainerSecurityContext

class TestIoFissionV1EnvironmentSpecBuilderContainerSecurityContext(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerSecurityContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerSecurityContext:
        """Test IoFissionV1EnvironmentSpecBuilderContainerSecurityContext
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerSecurityContext`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerSecurityContext()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerSecurityContext(
                allow_privilege_escalation = True,
                app_armor_profile = fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_app_armor_profile.io_fission_v1_Environment_spec_builder_container_securityContext_appArmorProfile(
                    localhost_profile = '', 
                    type = '', ),
                capabilities = fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_capabilities.io_fission_v1_Environment_spec_builder_container_securityContext_capabilities(
                    add = [
                        ''
                        ], 
                    drop = [
                        ''
                        ], ),
                privileged = True,
                proc_mount = '',
                read_only_root_filesystem = True,
                run_as_group = 56,
                run_as_non_root = True,
                run_as_user = 56,
                se_linux_options = fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_se_linux_options.io_fission_v1_Environment_spec_builder_container_securityContext_seLinuxOptions(
                    level = '', 
                    role = '', 
                    type = '', 
                    user = '', ),
                seccomp_profile = fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_seccomp_profile.io_fission_v1_Environment_spec_builder_container_securityContext_seccompProfile(
                    localhost_profile = '', 
                    type = '', ),
                windows_options = fission_client.models.io_fission_v1_environment_spec_builder_container_security_context_windows_options.io_fission_v1_Environment_spec_builder_container_securityContext_windowsOptions(
                    gmsa_credential_spec = '', 
                    gmsa_credential_spec_name = '', 
                    host_process = True, 
                    run_as_user_name = '', )
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerSecurityContext(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerSecurityContext(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerSecurityContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
