# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_canary_config_spec import IoFissionV1CanaryConfigSpec

class TestIoFissionV1CanaryConfigSpec(unittest.TestCase):
    """IoFissionV1CanaryConfigSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1CanaryConfigSpec:
        """Test IoFissionV1CanaryConfigSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1CanaryConfigSpec`
        """
        model = IoFissionV1CanaryConfigSpec()
        if include_optional:
            return IoFissionV1CanaryConfigSpec(
                duration = '',
                failure_type = '',
                failurethreshold = 56,
                newfunction = '',
                oldfunction = '',
                trigger = '',
                weightincrement = 56
            )
        else:
            return IoFissionV1CanaryConfigSpec(
                newfunction = '',
                oldfunction = '',
                trigger = '',
        )
        """

    def testIoFissionV1CanaryConfigSpec(self):
        """Test IoFissionV1CanaryConfigSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
