# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_canary_config_status import IoFissionV1CanaryConfigStatus

class TestIoFissionV1CanaryConfigStatus(unittest.TestCase):
    """IoFissionV1CanaryConfigStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1CanaryConfigStatus:
        """Test IoFissionV1CanaryConfigStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1CanaryConfigStatus`
        """
        model = IoFissionV1CanaryConfigStatus()
        if include_optional:
            return IoFissionV1CanaryConfigStatus(
                status = ''
            )
        else:
            return IoFissionV1CanaryConfigStatus(
                status = '',
        )
        """

    def testIoFissionV1CanaryConfigStatus(self):
        """Test IoFissionV1CanaryConfigStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
