# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_kubernetes_watch_trigger import IoFissionV1KubernetesWatchTrigger

class TestIoFissionV1KubernetesWatchTrigger(unittest.TestCase):
    """IoFissionV1KubernetesWatchTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1KubernetesWatchTrigger:
        """Test IoFissionV1KubernetesWatchTrigger
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1KubernetesWatchTrigger`
        """
        model = IoFissionV1KubernetesWatchTrigger()
        if include_optional:
            return IoFissionV1KubernetesWatchTrigger(
                api_version = '',
                kind = '',
                metadata = None,
                spec = fission_client.models.io_fission_v1_kubernetes_watch_trigger_spec.io_fission_v1_KubernetesWatchTrigger_spec(
                    functionref = fission_client.models.io_fission_v1_kubernetes_watch_trigger_spec_functionref.io_fission_v1_KubernetesWatchTrigger_spec_functionref(
                        functionweights = fission_client.models.functionweights.functionweights(), 
                        name = '', 
                        type = '', ), 
                    labelselector = {
                        'key' : ''
                        }, 
                    namespace = '', 
                    type = '', )
            )
        else:
            return IoFissionV1KubernetesWatchTrigger(
                metadata = None,
                spec = fission_client.models.io_fission_v1_kubernetes_watch_trigger_spec.io_fission_v1_KubernetesWatchTrigger_spec(
                    functionref = fission_client.models.io_fission_v1_kubernetes_watch_trigger_spec_functionref.io_fission_v1_KubernetesWatchTrigger_spec_functionref(
                        functionweights = fission_client.models.functionweights.functionweights(), 
                        name = '', 
                        type = '', ), 
                    labelselector = {
                        'key' : ''
                        }, 
                    namespace = '', 
                    type = '', ),
        )
        """

    def testIoFissionV1KubernetesWatchTrigger(self):
        """Test IoFissionV1KubernetesWatchTrigger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
