# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down import IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown

class TestIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown(unittest.TestCase):
    """IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown:
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown`
        """
        model = IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown()
        if include_optional:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown(
                policies = [
                    fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down_policies_inner.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown_policies_inner(
                        period_seconds = 56, 
                        type = '', 
                        value = 56, )
                    ],
                select_policy = '',
                stabilization_window_seconds = 56
            )
        else:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown(
        )
        """

    def testIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown(self):
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaBehaviorScaleDown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
