# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_security_context_app_armor_profile import IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile

class TestIoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile(
                localhost_profile = '',
                type = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile(
                type = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecSecurityContextAppArmorProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
