# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_volume_mounts_inner import IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner

class TestIoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner:
        """Test IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner(
                mount_path = '',
                mount_propagation = '',
                name = '',
                read_only = True,
                recursive_read_only = '',
                sub_path = '',
                sub_path_expr = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner(
                mount_path = '',
                name = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerVolumeMountsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
