# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_azure_disk import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk(
                caching_mode = '',
                disk_name = '',
                disk_uri = '',
                fs_type = '',
                kind = '',
                read_only = True
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk(
                disk_name = '',
                disk_uri = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerAzureDisk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
