# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_readiness_gates_inner import IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner

class TestIoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner(
                condition_type = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner(
                condition_type = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecReadinessGatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
