# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_package import IoFissionV1FunctionSpecPackage

class TestIoFissionV1FunctionSpecPackage(unittest.TestCase):
    """IoFissionV1FunctionSpecPackage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecPackage:
        """Test IoFissionV1FunctionSpecPackage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecPackage`
        """
        model = IoFissionV1FunctionSpecPackage()
        if include_optional:
            return IoFissionV1FunctionSpecPackage(
                function_name = '',
                packageref = fission_client.models.io_fission_v1_function_spec_package_packageref.io_fission_v1_Function_spec_package_packageref(
                    name = '', 
                    namespace = '', 
                    resourceversion = '', )
            )
        else:
            return IoFissionV1FunctionSpecPackage(
        )
        """

    def testIoFissionV1FunctionSpecPackage(self):
        """Test IoFissionV1FunctionSpecPackage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
