# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_canary_config_list import IoFissionV1CanaryConfigList

class TestIoFissionV1CanaryConfigList(unittest.TestCase):
    """IoFissionV1CanaryConfigList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1CanaryConfigList:
        """Test IoFissionV1CanaryConfigList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1CanaryConfigList`
        """
        model = IoFissionV1CanaryConfigList()
        if include_optional:
            return IoFissionV1CanaryConfigList(
                api_version = '',
                items = [
                    fission_client.models.io/fission/v1/canary_config.io.fission.v1.CanaryConfig(
                        api_version = '', 
                        kind = '', 
                        metadata = None, 
                        spec = fission_client.models.io_fission_v1_canary_config_spec.io_fission_v1_CanaryConfig_spec(
                            duration = '', 
                            failure_type = '', 
                            failurethreshold = 56, 
                            newfunction = '', 
                            oldfunction = '', 
                            trigger = '', 
                            weightincrement = 56, ), 
                        status = fission_client.models.io_fission_v1_canary_config_status.io_fission_v1_CanaryConfig_status(
                            status = '', ), )
                    ],
                kind = '',
                metadata = None
            )
        else:
            return IoFissionV1CanaryConfigList(
                items = [
                    fission_client.models.io/fission/v1/canary_config.io.fission.v1.CanaryConfig(
                        api_version = '', 
                        kind = '', 
                        metadata = None, 
                        spec = fission_client.models.io_fission_v1_canary_config_spec.io_fission_v1_CanaryConfig_spec(
                            duration = '', 
                            failure_type = '', 
                            failurethreshold = 56, 
                            newfunction = '', 
                            oldfunction = '', 
                            trigger = '', 
                            weightincrement = 56, ), 
                        status = fission_client.models.io_fission_v1_canary_config_status.io_fission_v1_CanaryConfig_status(
                            status = '', ), )
                    ],
        )
        """

    def testIoFissionV1CanaryConfigList(self):
        """Test IoFissionV1CanaryConfigList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
