# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_time_trigger import IoFissionV1TimeTrigger

class TestIoFissionV1TimeTrigger(unittest.TestCase):
    """IoFissionV1TimeTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1TimeTrigger:
        """Test IoFissionV1TimeTrigger
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1TimeTrigger`
        """
        model = IoFissionV1TimeTrigger()
        if include_optional:
            return IoFissionV1TimeTrigger(
                api_version = '',
                kind = '',
                metadata = None,
                spec = fission_client.models.io_fission_v1_time_trigger_spec.io_fission_v1_TimeTrigger_spec(
                    cron = '', 
                    functionref = fission_client.models.io_fission_v1_time_trigger_spec_functionref.io_fission_v1_TimeTrigger_spec_functionref(
                        functionweights = fission_client.models.functionweights.functionweights(), 
                        name = '', 
                        type = '', ), 
                    method = '', 
                    subpath = '', )
            )
        else:
            return IoFissionV1TimeTrigger(
                metadata = None,
                spec = fission_client.models.io_fission_v1_time_trigger_spec.io_fission_v1_TimeTrigger_spec(
                    cron = '', 
                    functionref = fission_client.models.io_fission_v1_time_trigger_spec_functionref.io_fission_v1_TimeTrigger_spec_functionref(
                        functionweights = fission_client.models.functionweights.functionweights(), 
                        name = '', 
                        type = '', ), 
                    method = '', 
                    subpath = '', ),
        )
        """

    def testIoFissionV1TimeTrigger(self):
        """Test IoFissionV1TimeTrigger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
