# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_package_packageref import IoFissionV1FunctionSpecPackagePackageref

class TestIoFissionV1FunctionSpecPackagePackageref(unittest.TestCase):
    """IoFissionV1FunctionSpecPackagePackageref unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecPackagePackageref:
        """Test IoFissionV1FunctionSpecPackagePackageref
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecPackagePackageref`
        """
        model = IoFissionV1FunctionSpecPackagePackageref()
        if include_optional:
            return IoFissionV1FunctionSpecPackagePackageref(
                name = '',
                namespace = '',
                resourceversion = ''
            )
        else:
            return IoFissionV1FunctionSpecPackagePackageref(
        )
        """

    def testIoFissionV1FunctionSpecPackagePackageref(self):
        """Test IoFissionV1FunctionSpecPackagePackageref"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
