# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_vsphere_volume import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume(
                fs_type = '',
                storage_policy_id = '',
                storage_policy_name = '',
                volume_path = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume(
                volume_path = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerVsphereVolume"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
