# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get import IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet

class TestIoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet:
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet(
                host = '',
                http_headers = [
                    fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get_http_headers_inner.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet_httpHeaders_inner(
                        name = '', 
                        value = '', )
                    ],
                path = '',
                port = fission_client.models.port.port(),
                scheme = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet(
                port = fission_client.models.port.port(),
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStartHttpGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
