# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner import IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner

class TestIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner(unittest.TestCase):
    """IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner:
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner`
        """
        model = IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner()
        if include_optional:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner(
                container_resource = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource(
                    container = '', 
                    name = '', 
                    target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                        average_utilization = 56, 
                        average_value = fission_client.models.average_value.averageValue(), 
                        type = '', 
                        value = fission_client.models.value.value(), ), ),
                external = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external(
                    metric = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric(
                        name = '', 
                        selector = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric_selector.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric_selector(
                            match_expressions = [
                                fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                        average_utilization = 56, 
                        average_value = fission_client.models.average_value.averageValue(), 
                        type = '', 
                        value = fission_client.models.value.value(), ), ),
                object = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_object.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_object(
                    described_object = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_object_described_object.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_object_describedObject(
                        api_version = '', 
                        kind = '', 
                        name = '', ), 
                    metric = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric(
                        name = '', 
                        selector = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric_selector.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric_selector(
                            match_expressions = [
                                fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                        average_utilization = 56, 
                        average_value = fission_client.models.average_value.averageValue(), 
                        type = '', 
                        value = fission_client.models.value.value(), ), ),
                pods = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_pods.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_pods(
                    metric = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric(
                        name = '', 
                        selector = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric_selector.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric_selector(
                            match_expressions = [
                                fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                        average_utilization = 56, 
                        average_value = fission_client.models.average_value.averageValue(), 
                        type = '', 
                        value = fission_client.models.value.value(), ), ),
                resource = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_resource.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_resource(
                    name = '', 
                    target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                        average_utilization = 56, 
                        average_value = fission_client.models.average_value.averageValue(), 
                        type = '', 
                        value = fission_client.models.value.value(), ), ),
                type = ''
            )
        else:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner(
                type = '',
        )
        """

    def testIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner(self):
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
