# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle import IoFissionV1EnvironmentSpecBuilderContainerLifecycle

class TestIoFissionV1EnvironmentSpecBuilderContainerLifecycle(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerLifecycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerLifecycle:
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecycle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerLifecycle`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerLifecycle()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecycle(
                post_start = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart(
                    exec = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_exec.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_exec(
                        command = [
                            ''
                            ], ), 
                    http_get = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet(
                        host = '', 
                        http_headers = [
                            fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get_http_headers_inner.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet_httpHeaders_inner(
                                name = '', 
                                value = '', )
                            ], 
                        path = '', 
                        port = fission_client.models.port.port(), 
                        scheme = '', ), 
                    sleep = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_sleep.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_sleep(
                        seconds = 56, ), 
                    tcp_socket = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_tcp_socket.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_tcpSocket(
                        host = '', 
                        port = fission_client.models.port.port(), ), ),
                pre_stop = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_pre_stop.io_fission_v1_Environment_spec_builder_container_lifecycle_preStop(
                    exec = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_exec.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_exec(
                        command = [
                            ''
                            ], ), 
                    http_get = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet(
                        host = '', 
                        http_headers = [
                            fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get_http_headers_inner.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet_httpHeaders_inner(
                                name = '', 
                                value = '', )
                            ], 
                        path = '', 
                        port = fission_client.models.port.port(), 
                        scheme = '', ), 
                    sleep = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_sleep.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_sleep(
                        seconds = 56, ), 
                    tcp_socket = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_tcp_socket.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_tcpSocket(
                        host = '', 
                        port = fission_client.models.port.port(), ), )
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerLifecycle(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerLifecycle(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerLifecycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
