# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity import IoFissionV1EnvironmentSpecBuilderPodspecAffinity

class TestIoFissionV1EnvironmentSpecBuilderPodspecAffinity(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecAffinity:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecAffinity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecAffinity`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecAffinity()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecAffinity(
                node_affinity = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner(
                            preference = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference(
                                match_expressions = [
                                    fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                        key = '', 
                                        operator = '', 
                                        values = [
                                            ''
                                            ], )
                                    ], 
                                match_fields = [
                                    fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_preferred_during_scheduling_ignored_during_execution_inner_preference_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_preference_matchExpressions_inner(
                                        key = '', 
                                        operator = '', )
                                    ], ), 
                            weight = 56, )
                        ], 
                    required_during_scheduling_ignored_during_execution = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_required_during_scheduling_ignored_during_execution.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution(
                        node_selector_terms = [
                            fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity_required_during_scheduling_ignored_during_execution_node_selector_terms_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution_nodeSelectorTerms_inner()
                            ], ), ),
                pod_affinity = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner(
                            pod_affinity_term = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm(
                                label_selector = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                                    match_expressions = [
                                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                            key = '', 
                                            operator = '', 
                                            values = [
                                                ''
                                                ], )
                                        ], 
                                    match_labels = {
                                        'key' : ''
                                        }, ), 
                                match_label_keys = [
                                    ''
                                    ], 
                                mismatch_label_keys = [
                                    ''
                                    ], 
                                namespace_selector = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_namespace_selector.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_namespaceSelector(), 
                                namespaces = [
                                    ''
                                    ], 
                                topology_key = '', ), 
                            weight = 56, )
                        ], 
                    required_during_scheduling_ignored_during_execution = [
                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_required_during_scheduling_ignored_during_execution_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_requiredDuringSchedulingIgnoredDuringExecution_inner(
                            topology_key = '', )
                        ], ),
                pod_anti_affinity = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_anti_affinity.io_fission_v1_Environment_spec_builder_podspec_affinity_podAntiAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner(
                            pod_affinity_term = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm(
                                label_selector = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector(
                                    match_expressions = [
                                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                            key = '', 
                                            operator = '', 
                                            values = [
                                                ''
                                                ], )
                                        ], 
                                    match_labels = {
                                        'key' : ''
                                        }, ), 
                                match_label_keys = [
                                    ''
                                    ], 
                                mismatch_label_keys = [
                                    ''
                                    ], 
                                namespace_selector = fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_namespace_selector.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_namespaceSelector(), 
                                namespaces = [
                                    ''
                                    ], 
                                topology_key = '', ), 
                            weight = 56, )
                        ], 
                    required_during_scheduling_ignored_during_execution = [
                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_required_during_scheduling_ignored_during_execution_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_requiredDuringSchedulingIgnoredDuringExecution_inner(
                            topology_key = '', )
                        ], )
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecAffinity(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecAffinity(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecAffinity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
