# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy import IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy

class TestIoFissionV1FunctionSpecInvokeStrategyExecutionStrategy(unittest.TestCase):
    """IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy:
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy`
        """
        model = IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy()
        if include_optional:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy(
                executor_type = '',
                max_scale = 56,
                min_scale = 56,
                specialization_timeout = 56,
                target_cpu_percent = 56,
                hpa_behavior = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior(
                    scale_down = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown(
                        policies = [
                            fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_down_policies_inner.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleDown_policies_inner(
                                period_seconds = 56, 
                                type = '', 
                                value = 56, )
                            ], 
                        select_policy = '', 
                        stabilization_window_seconds = 56, ), 
                    scale_up = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_behavior_scale_up.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaBehavior_scaleUp(
                        select_policy = '', 
                        stabilization_window_seconds = 56, ), ),
                hpa_metrics = [
                    fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner(
                        container_resource = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource(
                            container = '', 
                            name = '', 
                            target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                                average_utilization = 56, 
                                average_value = fission_client.models.average_value.averageValue(), 
                                type = '', 
                                value = fission_client.models.value.value(), ), ), 
                        external = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external(
                            metric = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric(
                                name = '', 
                                selector = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric_selector.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric_selector(
                                    match_expressions = [
                                        fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity_preferred_during_scheduling_ignored_during_execution_inner_pod_affinity_term_label_selector_match_expressions_inner.io_fission_v1_Environment_spec_builder_podspec_affinity_podAffinity_preferredDuringSchedulingIgnoredDuringExecution_inner_podAffinityTerm_labelSelector_matchExpressions_inner(
                                            key = '', 
                                            operator = '', 
                                            values = [
                                                ''
                                                ], )
                                        ], 
                                    match_labels = {
                                        'key' : ''
                                        }, ), ), 
                            target = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_container_resource_target.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_containerResource_target(
                                average_utilization = 56, 
                                average_value = fission_client.models.average_value.averageValue(), 
                                type = '', 
                                value = fission_client.models.value.value(), ), ), 
                        object = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_object.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_object(
                            described_object = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_object_described_object.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_object_describedObject(
                                api_version = '', 
                                kind = '', 
                                name = '', ), 
                            metric = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_external_metric.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_external_metric(
                                name = '', ), 
                            target = , ), 
                        pods = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_pods.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_pods(
                            metric = , 
                            target = , ), 
                        resource = fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_resource.io_fission_v1_Function_spec_InvokeStrategy_ExecutionStrategy_hpaMetrics_inner_resource(
                            name = '', 
                            target = , ), 
                        type = '', )
                    ]
            )
        else:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy(
        )
        """

    def testIoFissionV1FunctionSpecInvokeStrategyExecutionStrategy(self):
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
