# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_k8s_apimachinery_pkg_version_info import IoK8sApimachineryPkgVersionInfo

class TestIoK8sApimachineryPkgVersionInfo(unittest.TestCase):
    """IoK8sApimachineryPkgVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApimachineryPkgVersionInfo:
        """Test IoK8sApimachineryPkgVersionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApimachineryPkgVersionInfo`
        """
        model = IoK8sApimachineryPkgVersionInfo()
        if include_optional:
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '',
                compiler = '',
                git_commit = '',
                git_tree_state = '',
                git_version = '',
                go_version = '',
                major = '',
                minor = '',
                platform = ''
            )
        else:
            return IoK8sApimachineryPkgVersionInfo(
                build_date = '',
                compiler = '',
                git_commit = '',
                git_tree_state = '',
                git_version = '',
                go_version = '',
                major = '',
                minor = '',
                platform = '',
        )
        """

    def testIoK8sApimachineryPkgVersionInfo(self):
        """Test IoK8sApimachineryPkgVersionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
