# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy_hpa_metrics_inner_object_described_object import IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject

class TestIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject(unittest.TestCase):
    """IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject:
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject`
        """
        model = IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject()
        if include_optional:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject(
                api_version = '',
                kind = '',
                name = ''
            )
        else:
            return IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject(
                kind = '',
                name = '',
        )
        """

    def testIoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject(self):
        """Test IoFissionV1FunctionSpecInvokeStrategyExecutionStrategyHpaMetricsInnerObjectDescribedObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
