# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_startup_probe import IoFissionV1EnvironmentSpecBuilderContainerStartupProbe

class TestIoFissionV1EnvironmentSpecBuilderContainerStartupProbe(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerStartupProbe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerStartupProbe:
        """Test IoFissionV1EnvironmentSpecBuilderContainerStartupProbe
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerStartupProbe`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerStartupProbe()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerStartupProbe(
                var_exec = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_exec.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_exec(
                    command = [
                        ''
                        ], ),
                failure_threshold = 56,
                grpc = fission_client.models.io_fission_v1_environment_spec_builder_container_liveness_probe_grpc.io_fission_v1_Environment_spec_builder_container_livenessProbe_grpc(
                    port = 56, 
                    service = '', ),
                http_get = fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet(
                    host = '', 
                    http_headers = [
                        fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start_http_get_http_headers_inner.io_fission_v1_Environment_spec_builder_container_lifecycle_postStart_httpGet_httpHeaders_inner(
                            name = '', 
                            value = '', )
                        ], 
                    path = '', 
                    port = fission_client.models.port.port(), 
                    scheme = '', ),
                initial_delay_seconds = 56,
                period_seconds = 56,
                success_threshold = 56,
                tcp_socket = fission_client.models.io_fission_v1_environment_spec_builder_container_liveness_probe_tcp_socket.io_fission_v1_Environment_spec_builder_container_livenessProbe_tcpSocket(
                    host = '', 
                    port = fission_client.models.port.port(), ),
                termination_grace_period_seconds = 56,
                timeout_seconds = 56
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerStartupProbe(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerStartupProbe(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerStartupProbe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
