# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_container_env_inner_value_from import IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom

class TestIoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom:
        """Test IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom`
        """
        model = IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom(
                config_map_key_ref = fission_client.models.io_fission_v1_environment_spec_builder_container_env_inner_value_from_config_map_key_ref.io_fission_v1_Environment_spec_builder_container_env_inner_valueFrom_configMapKeyRef(
                    key = '', 
                    name = '', 
                    optional = True, ),
                field_ref = fission_client.models.io_fission_v1_environment_spec_builder_container_env_inner_value_from_field_ref.io_fission_v1_Environment_spec_builder_container_env_inner_valueFrom_fieldRef(
                    api_version = '', 
                    field_path = '', ),
                resource_field_ref = fission_client.models.io_fission_v1_environment_spec_builder_container_env_inner_value_from_resource_field_ref.io_fission_v1_Environment_spec_builder_container_env_inner_valueFrom_resourceFieldRef(
                    container_name = '', 
                    divisor = fission_client.models.divisor.divisor(), 
                    resource = '', ),
                secret_key_ref = fission_client.models.io_fission_v1_environment_spec_builder_container_env_inner_value_from_secret_key_ref.io_fission_v1_Environment_spec_builder_container_env_inner_valueFrom_secretKeyRef(
                    key = '', 
                    name = '', 
                    optional = True, )
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom(self):
        """Test IoFissionV1EnvironmentSpecBuilderContainerEnvInnerValueFrom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
