# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_config_map_items_inner import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner(
                key = '',
                mode = 56,
                path = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner(
                key = '',
                path = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerConfigMapItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
