# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_projected_sources_inner_secret import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret(
                items = [
                    fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_config_map_items_inner.io_fission_v1_Environment_spec_builder_podspec_volumes_inner_configMap_items_inner(
                        key = '', 
                        mode = 56, 
                        path = '', )
                    ],
                name = '',
                optional = True
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerProjectedSourcesInnerSecret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
