# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_package_spec_source import IoFissionV1PackageSpecSource

class TestIoFissionV1PackageSpecSource(unittest.TestCase):
    """IoFissionV1PackageSpecSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1PackageSpecSource:
        """Test IoFissionV1PackageSpecSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1PackageSpecSource`
        """
        model = IoFissionV1PackageSpecSource()
        if include_optional:
            return IoFissionV1PackageSpecSource(
                checksum = fission_client.models.io_fission_v1_package_spec_deployment_checksum.io_fission_v1_Package_spec_deployment_checksum(
                    sum = '', 
                    type = '', ),
                literal = 'YQ==',
                type = '',
                url = ''
            )
        else:
            return IoFissionV1PackageSpecSource(
        )
        """

    def testIoFissionV1PackageSpecSource(self):
        """Test IoFissionV1PackageSpecSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
