# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_downward_api_items_inner_field_ref import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef(
                api_version = '',
                field_path = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef(
                field_path = '',
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerDownwardAPIItemsInnerFieldRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
