# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fission_client.models.io_fission_v1_environment_spec_builder_podspec_volumes_inner_cinder_secret_ref import IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef

class TestIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef(unittest.TestCase):
    """IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef:
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef`
        """
        model = IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef()
        if include_optional:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef(
                name = ''
            )
        else:
            return IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef(
        )
        """

    def testIoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef(self):
        """Test IoFissionV1EnvironmentSpecBuilderPodspecVolumesInnerCinderSecretRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
