# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from fission_client.models.io_fission_v1_function_spec_invoke_strategy_execution_strategy import IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IoFissionV1FunctionSpecInvokeStrategy(BaseModel):
    """
    InvokeStrategy is a set of controls which affect how function executes
    """ # noqa: E501
    execution_strategy: Optional[IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy] = Field(default=None, alias="ExecutionStrategy")
    strategy_type: Optional[StrictStr] = Field(default=None, description="StrategyType is the strategy type of function. Now it only supports 'execution'.", alias="StrategyType")
    __properties: ClassVar[List[str]] = ["ExecutionStrategy", "StrategyType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IoFissionV1FunctionSpecInvokeStrategy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of execution_strategy
        if self.execution_strategy:
            _dict['ExecutionStrategy'] = self.execution_strategy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IoFissionV1FunctionSpecInvokeStrategy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ExecutionStrategy": IoFissionV1FunctionSpecInvokeStrategyExecutionStrategy.from_dict(obj.get("ExecutionStrategy")) if obj.get("ExecutionStrategy") is not None else None,
            "StrategyType": obj.get("StrategyType")
        })
        return _obj


