# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt
from pydantic import Field
from fission_client.models.io_fission_v1_function_spec_environment import IoFissionV1FunctionSpecEnvironment
from fission_client.models.io_fission_v1_function_spec_invoke_strategy import IoFissionV1FunctionSpecInvokeStrategy
from fission_client.models.io_fission_v1_function_spec_package import IoFissionV1FunctionSpecPackage
from fission_client.models.io_fission_v1_function_spec_podspec import IoFissionV1FunctionSpecPodspec
from fission_client.models.io_fission_v1_function_spec_resources import IoFissionV1FunctionSpecResources
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IoFissionV1FunctionSpec(BaseModel):
    """
    FunctionSpec describes the contents of the function.
    """ # noqa: E501
    invoke_strategy: IoFissionV1FunctionSpecInvokeStrategy = Field(alias="InvokeStrategy")
    concurrency: Optional[StrictInt] = Field(default=None, description="Maximum number of pods to be specialized which will serve requests This is optional. If not specified default value will be taken as 500")
    configmaps: Optional[Dict[str, Any]] = Field(default=None, description="Reference to a list of configmaps.")
    environment: IoFissionV1FunctionSpecEnvironment
    function_timeout: Optional[StrictInt] = Field(default=None, description="FunctionTimeout provides a maximum amount of duration within which a request for a particular function execution should be complete. This is optional. If not specified default value will be taken as 60s", alias="functionTimeout")
    idletimeout: Optional[StrictInt] = Field(default=None, description="IdleTimeout specifies the length of time that a function is idle before the function pod(s) are eligible for deletion. If no traffic to the function is detected within the idle timeout, the executor will then recycle the function pod(s) to release resources.")
    once_only: Optional[StrictBool] = Field(default=None, description="OnceOnly specifies if specialized pod will serve exactly one request in its lifetime and would be garbage collected after serving that one request This is optional. If not specified default value will be taken as false", alias="onceOnly")
    package: IoFissionV1FunctionSpecPackage
    podspec: Optional[IoFissionV1FunctionSpecPodspec] = None
    requests_per_pod: Optional[StrictInt] = Field(default=None, description="RequestsPerPod indicates the maximum number of concurrent requests that can be served by a specialized pod This is optional. If not specified default value will be taken as 1", alias="requestsPerPod")
    resources: Optional[IoFissionV1FunctionSpecResources] = None
    retain_pods: Optional[StrictInt] = Field(default=None, description="RetainPods specifies the number of specialized pods that should be retained after serving requests This is optional. If not specified default value will be taken as 0", alias="retainPods")
    secrets: Optional[Dict[str, Any]] = Field(default=None, description="Reference to a list of secrets.")
    __properties: ClassVar[List[str]] = ["InvokeStrategy", "concurrency", "configmaps", "environment", "functionTimeout", "idletimeout", "onceOnly", "package", "podspec", "requestsPerPod", "resources", "retainPods", "secrets"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IoFissionV1FunctionSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of invoke_strategy
        if self.invoke_strategy:
            _dict['InvokeStrategy'] = self.invoke_strategy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of environment
        if self.environment:
            _dict['environment'] = self.environment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of package
        if self.package:
            _dict['package'] = self.package.to_dict()
        # override the default output from pydantic by calling `to_dict()` of podspec
        if self.podspec:
            _dict['podspec'] = self.podspec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IoFissionV1FunctionSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "InvokeStrategy": IoFissionV1FunctionSpecInvokeStrategy.from_dict(obj.get("InvokeStrategy")) if obj.get("InvokeStrategy") is not None else None,
            "concurrency": obj.get("concurrency"),
            "configmaps": obj.get("configmaps"),
            "environment": IoFissionV1FunctionSpecEnvironment.from_dict(obj.get("environment")) if obj.get("environment") is not None else None,
            "functionTimeout": obj.get("functionTimeout"),
            "idletimeout": obj.get("idletimeout"),
            "onceOnly": obj.get("onceOnly"),
            "package": IoFissionV1FunctionSpecPackage.from_dict(obj.get("package")) if obj.get("package") is not None else None,
            "podspec": IoFissionV1FunctionSpecPodspec.from_dict(obj.get("podspec")) if obj.get("podspec") is not None else None,
            "requestsPerPod": obj.get("requestsPerPod"),
            "resources": IoFissionV1FunctionSpecResources.from_dict(obj.get("resources")) if obj.get("resources") is not None else None,
            "retainPods": obj.get("retainPods"),
            "secrets": obj.get("secrets")
        })
        return _obj


