# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_node_affinity import IoFissionV1EnvironmentSpecBuilderPodspecAffinityNodeAffinity
from fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_affinity import IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAffinity
from fission_client.models.io_fission_v1_environment_spec_builder_podspec_affinity_pod_anti_affinity import IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAntiAffinity
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IoFissionV1EnvironmentSpecBuilderPodspecAffinity(BaseModel):
    """
    If specified, the pod's scheduling constraints
    """ # noqa: E501
    node_affinity: Optional[IoFissionV1EnvironmentSpecBuilderPodspecAffinityNodeAffinity] = Field(default=None, alias="nodeAffinity")
    pod_affinity: Optional[IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAffinity] = Field(default=None, alias="podAffinity")
    pod_anti_affinity: Optional[IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAntiAffinity] = Field(default=None, alias="podAntiAffinity")
    __properties: ClassVar[List[str]] = ["nodeAffinity", "podAffinity", "podAntiAffinity"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IoFissionV1EnvironmentSpecBuilderPodspecAffinity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of node_affinity
        if self.node_affinity:
            _dict['nodeAffinity'] = self.node_affinity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pod_affinity
        if self.pod_affinity:
            _dict['podAffinity'] = self.pod_affinity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pod_anti_affinity
        if self.pod_anti_affinity:
            _dict['podAntiAffinity'] = self.pod_anti_affinity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IoFissionV1EnvironmentSpecBuilderPodspecAffinity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeAffinity": IoFissionV1EnvironmentSpecBuilderPodspecAffinityNodeAffinity.from_dict(obj.get("nodeAffinity")) if obj.get("nodeAffinity") is not None else None,
            "podAffinity": IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAffinity.from_dict(obj.get("podAffinity")) if obj.get("podAffinity") is not None else None,
            "podAntiAffinity": IoFissionV1EnvironmentSpecBuilderPodspecAffinityPodAntiAffinity.from_dict(obj.get("podAntiAffinity")) if obj.get("podAntiAffinity") is not None else None
        })
        return _obj


