# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.30.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_post_start import IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStart
from fission_client.models.io_fission_v1_environment_spec_builder_container_lifecycle_pre_stop import IoFissionV1EnvironmentSpecBuilderContainerLifecyclePreStop
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IoFissionV1EnvironmentSpecBuilderContainerLifecycle(BaseModel):
    """
    Actions that the management system should take in response to container lifecycle events. Cannot be updated.
    """ # noqa: E501
    post_start: Optional[IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStart] = Field(default=None, alias="postStart")
    pre_stop: Optional[IoFissionV1EnvironmentSpecBuilderContainerLifecyclePreStop] = Field(default=None, alias="preStop")
    __properties: ClassVar[List[str]] = ["postStart", "preStop"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IoFissionV1EnvironmentSpecBuilderContainerLifecycle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of post_start
        if self.post_start:
            _dict['postStart'] = self.post_start.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pre_stop
        if self.pre_stop:
            _dict['preStop'] = self.pre_stop.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IoFissionV1EnvironmentSpecBuilderContainerLifecycle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "postStart": IoFissionV1EnvironmentSpecBuilderContainerLifecyclePostStart.from_dict(obj.get("postStart")) if obj.get("postStart") is not None else None,
            "preStop": IoFissionV1EnvironmentSpecBuilderContainerLifecyclePreStop.from_dict(obj.get("preStop")) if obj.get("preStop") is not None else None
        })
        return _obj


